# This is a Render service configuration file for the demand-api web service. Using this is optional, but it allows you to specify how your service should be built and run on Render. For more information, see https://render.com/docs/render-yaml.
# We are using Docker for full deployment control, so this file is not strictly necessary. However, it can be useful for local development and testing.
services:
  - type: web
    name: demand-api
    envVars:
      - key: ENABLE_PROPHET
        value: "1"
    dockerfilePath: ./Dockerfile
    plan: free
    autoDeploy: true